function SlideShow(element,width,height,transition){this.element=element;this.images=[];this.controls={};this.transition=transition||'fade';var currentWidth=this.element.width();if(!width||width>currentWidth){width=currentWidth;}
this.width=width;this.height=height;this.element.css({'height':this.height+'px'});}
SlideShow.prototype.showLoadingImage=function(toggle){if(toggle){this.loadingImage_=document.createElement('div');this.loadingImage_.className='slideshow-loading';var img=document.createElement('img');img.src=WP_SLIDESHOW_IMAGES.load;this.loadingImage_.appendChild(img);this.loadingImage_.appendChild(this.makeZeroWidthSpan());this.loadingImage_.style.lineHeight=this.height+'px';this.element.append(this.loadingImage_);}else if(this.loadingImage_){this.loadingImage_.parentNode.removeChild(this.loadingImage_);this.loadingImage_=null;}};SlideShow.prototype.init=function(){this.showLoadingImage(true);var self=this;for(var i=0;i<this.images.length;i++){var imageInfo=this.images[i];var img=document.createElement('img');img.src=imageInfo.src+'?w='+this.width;img.align='middle';var caption=document.createElement('div');caption.className='slideshow-slide-caption';caption.innerHTML=imageInfo.caption;var container=document.createElement('div');container.className='slideshow-slide';container.style.lineHeight=this.height+'px';if(i==0){if(img.complete){setTimeout(function(){self.finishInit_();},1);}else{jQuery(img).load(function(){self.finishInit_();});}}
container.appendChild(img);img.removeAttribute('width');img.removeAttribute('height');container.appendChild(this.makeZeroWidthSpan());container.appendChild(caption);this.element.append(container);}};SlideShow.prototype.makeZeroWidthSpan=function(){var emptySpan=document.createElement('span');emptySpan.className='slideshow-line-height-hack';if(jQuery.browser.msie){emptySpan.appendChild(document.createTextNode(' '));}else{emptySpan.innerHTML='&nbsp;';}
return emptySpan;};SlideShow.prototype.finishInit_=function(){this.showLoadingImage(false);this.renderControls_();var self=this;this.element.cycle({fx:this.transition,prev:this.controls.prev,next:this.controls.next,slideExpr:'.slideshow-slide',onPrevNextEvent:function(){return self.onCyclePrevNextClick_.apply(self,arguments);}});var slideshow=this.element;jQuery(this.controls['stop']).click(function(){var button=jQuery(this);var icon;if(!button.hasClass('paused')){slideshow.cycle('pause');button.removeClass(' running ');button.addClass('paused');icon='play';}else{button.addClass('running');button.removeClass('paused');slideshow.cycle('resume',true);icon='stop';}
button.children('img').attr('src',WP_SLIDESHOW_IMAGES[icon]);return false;});var controls=jQuery(this.controlsDiv_);slideshow.mouseenter(function(){controls.fadeIn();});slideshow.mouseleave(function(){controls.fadeOut();});this.initialized_=true;};SlideShow.prototype.renderControls_=function(){if(this.controlsDiv_){return;}
var controlsDiv=document.createElement('div');controlsDiv.className='slideshow-controls';controls=['prev','stop','next'];for(var i=0;i<controls.length;i++){var controlName=controls[i];var a=document.createElement('a');a.href='#';var img=a.appendChild(document.createElement('img'));img.src=WP_SLIDESHOW_IMAGES[controlName];img.alt=WP_SLIDESHOW_LABELS[controlName];img.width='24';img.height='24';controlsDiv.appendChild(a);this.controls[controlName]=a;}
this.element.append(controlsDiv);this.controlsDiv_=controlsDiv;};SlideShow.prototype.onCyclePrevNextClick_=function(isNext,i,slideElement){var postid=this.images[i].id;var stats=new Image();stats.src=document.location.protocol+
'//stats.wordpress.com/g.gif?host='+
escape(document.location.host)+
'&rand='+Math.random()+
'&blog='+WP_SLIDESHOW_BLOG_INFO.blogId+
'&subd='+WP_SLIDESHOW_BLOG_INFO.subDomain+
'&user_id='+WP_SLIDESHOW_BLOG_INFO.userId+
'&post='+postid+
'&ref='+escape(document.location);};