var wpFollowButton;(function($){wpFollowButton={enable:function(){$('a.wpcom-follow, a.wpcom-following').click(function(e){e.preventDefault();var link=$(this);var ln_classes=link.attr('class').split(' ');for(i=0;i<ln_classes.length;i++){if(0==ln_classes[i].indexOf('f-')){var blog_id=ln_classes[i].slice(2,ln_classes[i].length);}}
var is_following=link.hasClass('wpcom-following');if(is_following){var action='ab_unsubscribe_from_blog';}else{var action='ab_subscribe_to_blog';}
var elem=$('a.f-'+blog_id);if(is_following){elem.fadeOut('fast',function(){elem.removeClass('wpcom-following').addClass('wpcom-follow').html('Follow');elem.fadeIn('fast');})}else{elem.fadeOut('fast',function(){elem.addClass('wpcom-following').removeClass('wpcom-follow').html('Following');elem.fadeIn('fast');})}
var href=link.attr('href');var params=href.split('\?');var domain=params[0];var flds=params[1].split('&');for(var i=0;i<flds.length;i++){var pos=flds[i].indexOf('=');if(-1==pos)continue;var argname=flds[i].substring(0,pos);var value=flds[i].substring(pos+1);if(argname=='_wpnonce'){var nonce=value;}else if(argname=='src'){var source=value;}}
$.post(domain+'wp-admin/admin-ajax.php',{'action':action,'_wpnonce':nonce,'blog_id':blog_id,'source':source},function(response){if('object'==typeof response.errors){if(is_following)
elem.removeClass('wpcom-follow').addClass('wpcom-following').html('Following');else
elem.removeClass('wpcom-following').addClass('wpcom-follow').html('Follow');}});});},enable_rest:function(){$('a.wpcom-follow-rest, a.wpcom-following-rest').click(function(e){e.preventDefault();var link=$(this);var blog_id=link.attr('data-blog-id');var is_following=link.hasClass('wpcom-following-rest');if(is_following){var rest_path='/sites/'+blog_id+'/follows/mine/delete';}else{var rest_path='/sites/'+blog_id+'/follows/new';}
var attr_selector='data-blog-id="'+blog_id+'"';var elem=$('a.wpcom-follow-rest['+attr_selector+'], a.wpcom-follow-rest['+attr_selector+']');if(is_following){elem.fadeOut('fast',function(){elem.removeClass('wpcom-following-rest').addClass('wpcom-follow-rest').html(link.attr('data-follow-text'));elem.fadeIn('fast');})}else{elem.fadeOut('fast',function(){elem.addClass('wpcom-following-rest').removeClass('wpcom-follow-rest').html(link.attr('data-following-text'));elem.fadeIn('fast');})}
jQuery.wpcom_proxy_request({method:'POST',path:rest_path},function(response,statusCode){console.error(response);if((200!=statusCode)||!response.success){if(is_following)
elem.removeClass('wpcom-follow-rest').addClass('wpcom-following-rest').html(link.attr('data-following-text'));else
elem.removeClass('wpcom-following-rest').addClass('wpcom-follow-rest').html(link.attr('data-follow-text'));}});});$('a.wpcom-following-rest').hover(function(){var link=$(this);var is_following=link.hasClass('wpcom-following-rest');if(is_following)
link.html(link.attr('data-following-hover-text'));},function(){var link=$(this);var is_following=link.hasClass('wpcom-following-rest');if(is_following)
link.html(link.attr('data-following-text'));});},create:function(data){var is_following=data['params']['is_following'];var follow_button=$('<a></a>',{'class':(is_following?'wpcom-following-rest':'wpcom-follow-rest'),href:'http://public-api.wordpress.com/sites/'+data['params']['blog_id']+'/follows',title:data['params']['blog_title']+
'('+data['params']['blog_domain']+')',html:is_following?data['params']['following-text']:data['params']['follow-text']}).attr({'data-blog-id':data['params']['blog_id'],'data-stat-src':data['params']['stat-source'],'data-follow-text':data['params']['follow-text'],'data-following-text':data['params']['following-text'],'data-following-hover-text':data['params']['following-hover-text'],});return follow_button;}};$(function(){wpFollowButton.enable()});})(jQuery);